import * as admin from 'firebase-admin';

if (admin.apps.length === 0) {
  admin.initializeApp();
}

export const db = admin.firestore();

export const COLLECTION_SEASON = 'PLAY_SEASON';
export const COLLECTION_PLAYER = 'PLAY_PLAYER';
export const COLLECTION_PLAYER_ASSET = 'PLAY_PLAYER_ASSET';
export const COLLECTION_BATCH = 'PLAY_BATCH';
export const COLLECTION_BATCH_CHUNKS = 'PLAY_BATCH_CHUNKS';
export const COLLECTION_IDEMPOTENCY_LOGS = 'PLAY_IDEMPOTENCY_LOGS';
export const COLLECTION_DECISION_LOG = 'PLAY_DECISION_LOG'; 
export const COLLECTION_PROPERTY_MASTER = 'PLAY_PROPERTY_MASTER';
export const COLLECTION_PRIMARY_SUPPLY = 'PLAY_PRIMARY_SUPPLY';
export const COLLECTION_PROPERTY_OWNERSHIP = 'PLAY_PROPERTY_OWNERSHIP';
export const COLLECTION_SECONDARY_LISTING = 'PLAY_SECONDARY_LISTING';
export const COLLECTION_SECONDARY_ORDER = 'PLAY_SECONDARY_ORDER';
export const COLLECTION_PROPERTY_TRANSACTION = 'PLAY_PROPERTY_TRANSACTION';
export const COLLECTION_LOAN = 'PLAY_LOAN';
