# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Weekly Update

on:
  schedule:    
    - cron: "0 21 * * 1"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
    - name: get Weekly MoneyFlow Update
      run: |
        python ./moneyflow/Moneyflow.py
    - name: Commits
      run: |        
        git pull
        git config --local user.email "aptranking@gmail.com"
        git config --local user.name "APT-Rank"
        git add ./moneyflow/market_moneyflow.json
        git commit -m "Weekly MoneyFlow Update"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        
